# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # tell Netlify's secrets scanner to ignore Supabase keys
  SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_ANON_KEY,VITE_SUPABASE_URL"
